---
galaxy_info:
    role_name: system
    author: Thomas Kiss
    description: Base packages, boot target, console keymap and verbose boot
    license: MIT
    min_ansible_version: "2.15"
    platforms:
        - name: Ubuntu
          versions:
              - noble
dependencies: []
