set -s set-clipboard on
set -s copy-command 'DISPLAY=${DISPLAY:-:0} xclip -selection clipboard'
set -g mouse on
set -g allow-rename off
set -g default-terminal "tmux-256color"
set -ag terminal-features ",$TERM:RGB"
set -as terminal-features ",$TERM:clipboard"
set -g focus-events on
set -g renumber-windows on
set -g history-limit 100000

bind -n M-Left previous-window
bind -n M-Right next-window
bind -n S-M-Left select-pane -L
bind -n S-M-Right select-pane -R
bind -n S-M-Up select-pane -U
bind -n S-M-Down select-pane -D

bind 'c' new-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind 'r' source-file ~/.tmux.conf

set-window-option -g mode-keys vi

# run-shell ~/.tmux/plugins/tmux-smooth-scroll/smooth-scroll.tmux

# set -g @smooth-scroll-mouse "true"

bind -n M-g if-shell -F '#{m:popup-*,#{session_name}}' {
  detach-client
} {
  run-shell -b '~/.tmux/popup.sh shell #{q:session_name} #{q:pane_current_path} #{q:client_name}'
}

bind -n M-c if-shell -F '#{m:popup-*,#{session_name}}' {
  detach-client
} {
  run-shell -b '~/.tmux/popup.sh ai #{q:session_name} #{q:pane_current_path} #{q:client_name}'
}
